## Análisis datos Covid

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [6]:

df_covid=pd.read_csv("COVID_2020/200419COVID19MEXICO.csv")
df_covid.head(10)

,FECHA_ACTUALIZACION,ID_REGISTRO,ORIGEN,SECTOR,ENTIDAD_UM,SEXO,ENTIDAD_NAC,ENTIDAD_RES,MUNICIPIO_RES,TIPO_PACIENTE,...,CARDIOVASCULAR,OBESIDAD,RENAL_CRONICA,TABAQUISMO,OTRO_CASO,RESULTADO,MIGRANTE,PAIS_NACIONALIDAD,PAIS_ORIGEN,UCI
0,2020-04-19,09e8dc,2,9,15,1,15,15,37.0,2,...,2,2,2,2,2,1,99,99,97,1
1,2020-04-19,1dd782,2,12,9,1,15,9,3.0,1,...,2,1,2,2,2,2,99,99,97,97
2,2020-04-19,0efbaf,2,9,28,2,16,28,32.0,1,...,2,2,2,2,1,1,99,99,97,97
3,2020-04-19,0e8ab4,2,12,9,2,99,9,13.0,1,...,2,2,2,2,1,3,99,99,97,97
4,2020-04-19,013a6c,1,3,15,2,15,15,106.0,1,...,2,1,2,2,1,3,99,99,97,97
5,2020-04-19,091a48,1,12,15,2,15,15,31.0,2,...,2,2,2,2,2,2,99,99,97,2
6,2020-04-19,1a5595,2,12,9,2,99,9,8.0,1,...,2,2,2,2,1,2,99,99,97,97
7,2020-04-19,13236c,1,4,2,2,21,2,4.0,2,...,2,1,2,2,99,2,99,México,97,2
8,2020-04-19,0cdb12,1,12,9,2,99,9,12.0,2,...,2,2,2,2,2,1,99,México,97,2
9,2020-04-19,038dad,1,12,9,1,99,9,14.0,1,...,2,2,2,2,1,1,99,México,97,97

In [5]:
df_covid.columns

Index(['FECHA_ACTUALIZACION', 'ID_REGISTRO', 'ORIGEN', 'SECTOR', 'ENTIDAD_UM',
       'SEXO', 'ENTIDAD_NAC', 'ENTIDAD_RES', 'MUNICIPIO_RES', 'TIPO_PACIENTE',
       'FECHA_INGRESO', 'FECHA_SINTOMAS', 'FECHA_DEF', 'INTUBADO', 'NEUMONIA',
       'EDAD', 'NACIONALIDAD', 'EMBARAZO', 'HABLA_LENGUA_INDIG', 'DIABETES',
       'EPOC', 'ASMA', 'INMUSUPR', 'HIPERTENSION', 'OTRA_COM',
       'CARDIOVASCULAR', 'OBESIDAD', 'RENAL_CRONICA', 'TABAQUISMO',
       'OTRO_CASO', 'RESULTADO', 'MIGRANTE', 'PAIS_NACIONALIDAD',
       'PAIS_ORIGEN', 'UCI'],
      dtype='object')

In [21]:
df_covid['SEXO'].value_counts()

SEXO
1    25264
2    24306
Name: count, dtype: int64

In [11]:
df_covid.groupby('SEXO')['ASMA'].sum()

SEXO
1    55216
2    57115
Name: ASMA, dtype: int64

In [14]:
df_covid['PAIS_NACIONALIDAD'].value_counts().head(5)

PAIS_NACIONALIDAD
México                       29347
99                           19254
Estados Unidos de América      280
España                          79
Colombia                        62
Name: count, dtype: int64

In [17]:
df_covid.groupby('MIGRANTE')['TABAQUISMO'].mean()

MIGRANTE
1     1.876289
2     2.481481
99    2.216422
Name: TABAQUISMO, dtype: float64

In [34]:
covid_yuc=df_covid[df_covid['ENTIDAD_NAC']==31]
covid_yuc.groupby('RESULTADO')['EDAD'].median().reset_index()

   RESULTADO  EDAD
0          1  45.0
1          2  37.0
2          3  40.0